    location /myaddresses/mon/api/ {
        auth_basic 'Hunter Monitor';
        auth_basic_user_file /etc/nginx/.htpasswd_hunter;
        rewrite ^/myaddresses/mon/api/(.*)$ /api/$1 break;
        proxy_pass http://127.0.0.1:7801;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
