// gl_fallback_embed_win.cpp — Windows-only. See include/core/gl_fallback_embed.h.
#include "core/gl_fallback_embed.h"

#include <windows.h>

#include <cstdio>
#include <cstdint>
#include <filesystem>
#include <vector>

#include "zstd.h"
#include "gl_fallback_embedded.h" // generated by tools/embed_gl_fallback.py

namespace hunter {
namespace embed {

namespace {

std::filesystem::path exeDir() {
    char exePath[MAX_PATH];
    GetModuleFileNameA(nullptr, exePath, MAX_PATH);
    return std::filesystem::path(exePath).parent_path();
}

// Decompresses one embedded zstd blob and writes it to `dest`. No-op (returns
// true) if `dest` already exists and is non-empty — we never overwrite a
// working extraction, and this doubles as the idempotency check that lets
// ensureGlFallbackExtracted() be called unconditionally.
bool extractOne(const unsigned char* zst, unsigned long zstLen, unsigned long origLen,
                 const std::filesystem::path& dest) {
    std::error_code ec;
    if (std::filesystem::exists(dest, ec) && std::filesystem::file_size(dest, ec) > 0) {
        return true;
    }
    if (zstLen == 0 || origLen == 0) return false;

    std::vector<uint8_t> buf(origLen);
    size_t r = ZSTD_decompress(buf.data(), origLen, zst, zstLen);
    if (ZSTD_isError(r) || r != origLen) return false;

    // Write to a temp file then rename — avoids a half-written DLL if we
    // crash mid-write (extraction happens right before a self-relaunch).
    auto tmp = dest;
    tmp += ".tmp";
    FILE* f = std::fopen(tmp.string().c_str(), "wb");
    if (!f) return false;
    size_t written = std::fwrite(buf.data(), 1, buf.size(), f);
    std::fclose(f);
    if (written != buf.size()) {
        std::filesystem::remove(tmp, ec);
        return false;
    }
    std::filesystem::rename(tmp, dest, ec);
    return !ec;
}

} // namespace

bool hasEmbeddedGlFallback() {
#if defined(HUNTER_GL_FALLBACK_EMBEDDED) && HUNTER_GL_FALLBACK_EMBEDDED
    return true;
#else
    return false;
#endif
}

bool glFallbackAlreadyPresent() {
    std::error_code ec;
    auto dir = exeDir();
    bool opengl = std::filesystem::exists(dir / "opengl32.dll", ec) &&
                  std::filesystem::file_size(dir / "opengl32.dll", ec) > 0;
    bool gallium = std::filesystem::exists(dir / "libgallium_wgl.dll", ec) &&
                   std::filesystem::file_size(dir / "libgallium_wgl.dll", ec) > 0;
    return opengl && gallium;
}

bool ensureGlFallbackExtracted() {
#if defined(HUNTER_GL_FALLBACK_EMBEDDED) && HUNTER_GL_FALLBACK_EMBEDDED
    auto dir = exeDir();
    bool ok1 = extractOne(kGlFallbackLoaderZst, kGlFallbackLoaderZstLen,
                           kGlFallbackLoaderOrigLen, dir / "opengl32.dll");
    bool ok2 = extractOne(kGlFallbackDriverZst, kGlFallbackDriverZstLen,
                           kGlFallbackDriverOrigLen, dir / "libgallium_wgl.dll");
    return ok1 && ok2;
#else
    return false;
#endif
}

} // namespace embed
} // namespace hunter
