#!/usr/bin/env python3
"""
embed_configs.py — Bake the downloaded proxy-config bundle into the Hunter
executable via .incbin (assembler include).

Complements embed_engines.py: where that script embeds xray + sing-box
binaries, this one embeds the config bundle (one URI per line, zstd-compressed)
so the single-file binary ships with a full working config set on first launch.

Outputs (into the build tree, never committed):
  - config_embedded.h    : small header with #defines, extern decls, sizes, SHA-256
  - config_embedded.S    : assembler file with .incbin directives
  - configs.zst          : zstd-compressed config bundle
  - config_meta.json     : metadata (count, sizes, digest) for manifest

If the config bundle is missing, HUNTER_EMBED_HAS_CONFIGS is set to 0 and the
runtime falls back to scraping sources live (the classic behavior).

Usage:
  embed_configs.py --bundle <configs.txt> --outdir <build_dir>
                   [--zstd <path>] [--no-zstd]
                   [--platform <windows|linux|android>]
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def zstd_compress(path: Path, zstd_bin: str, out_path: Path) -> bytes:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [zstd_bin, "-19", "-f", "-q", "-o", str(out_path), str(path)]
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out_path.read_bytes()


def count_lines(path: Path) -> int:
    n = 0
    with open(path, "r", errors="replace") as f:
        for line in f:
            if line.strip():
                n += 1
    return n


def main():
    ap = argparse.ArgumentParser(description="Embed config bundle via .incbin.")
    ap.add_argument("--bundle", required=True, help="Path to configs.txt (one URI per line).")
    ap.add_argument("--outdir", required=True, help="Output directory for generated files.")
    ap.add_argument("--zstd", default=shutil.which("zstd") or "zstd", help="zstd CLI path.")
    ap.add_argument("--no-zstd", action="store_true", help="Embed raw bytes (no compression).")
    ap.add_argument("--platform", default=None,
                    help="Target platform: 'windows' or 'linux'/'android'. "
                         "Defaults to host OS. Controls .rdata vs .rodata section.")
    args = ap.parse_args()

    bundle = Path(args.bundle)
    out_dir = Path(args.outdir)
    out_dir.mkdir(parents=True, exist_ok=True)

    is_win = os.name == "nt"
    use_zstd = not args.no_zstd
    if use_zstd and not shutil.which(args.zstd):
        print(f"[cfg-embed] WARNING: zstd CLI '{args.zstd}' not found; raw embed.", file=sys.stderr)
        use_zstd = False

    have_bundle = bundle.exists() and bundle.stat().st_size > 0
    if not have_bundle:
        print(f"[cfg-embed] bundle not found at {bundle} — emitting empty payload.", file=sys.stderr)

    # ─── Generate config_embedded.h ───
    header_lines = [
        "// AUTO-GENERATED by tools/embed_configs.py — DO NOT EDIT.",
        "// Embedded proxy-config bundle for the single-file Hunter build.",
        f"// Compressed with zstd (-19): {use_zstd if have_bundle else 'n/a'}",
        "// Actual byte array is provided by config_embedded.S via .incbin.",
        "",
        "#pragma once",
        "",
        f"#define HUNTER_EMBED_HAS_CONFIGS {1 if have_bundle else 0}",
        f"#define HUNTER_EMBED_CONFIGS_USE_ZSTD {1 if (use_zstd and have_bundle) else 0}",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "extern const unsigned char kConfigsZst[];",
        "extern const unsigned long  kConfigsZstLen;",
        f"static const unsigned long  kConfigsOrigLen = {bundle.stat().st_size if have_bundle else 0};",
        f"static const char           kConfigsSha256[] = \"\";",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    (out_dir / "config_embedded.h").write_text("\n".join(header_lines))

    # Compute metadata + compress.
    orig_size = 0
    embed_size = 0
    sha256 = ""
    config_count = 0
    zst_filename = ""

    if have_bundle:
        raw = bundle.read_bytes()
        orig_size = len(raw)
        sha256 = hashlib.sha256(raw).hexdigest()
        config_count = count_lines(bundle)
        ext = ".zst" if use_zstd else ".bin"
        blob_path = out_dir / f"configs{ext}"
        if use_zstd:
            comp = zstd_compress(bundle, args.zstd, blob_path)
        else:
            shutil.copy2(bundle, blob_path)
            comp = blob_path.read_bytes()
        embed_size = len(comp)
        zst_filename = blob_path.name
        ratio = (embed_size / orig_size * 100.0) if orig_size else 0.0
        print(f"[cfg-embed] {config_count} configs: {orig_size} -> {embed_size} bytes "
              f"({ratio:.1f}%) sha256={sha256[:12]}...")

    # ─── Generate config_embedded.S ───
    if args.platform:
        target_win = args.platform.lower() in ("windows", "win", "mingw", "win32")
    else:
        target_win = is_win

    asm_lines = [
        "// AUTO-GENERATED by tools/embed_configs.py — DO NOT EDIT.",
        "// Assembler file that embeds the compressed config bundle via .incbin.",
        "// Self-contained — no #include.",
        "",
    ]
    # Custom section on Windows rather than .rdata — see embed_engines.py for
    # why: a multi-MB maximum-entropy blob inside .rdata is a static "looks
    # packed" trigger for AV/EDR heuristics; a distinctly-named section avoids
    # that specific signal without changing anything at runtime.
    if target_win:
        asm_lines.append('    .section .hunterdat,"dr"')
    else:
        asm_lines.append('    .section .rodata')
    asm_lines.append("")

    if have_bundle and zst_filename:
        asm_lines.append(f"// ─── config bundle ({embed_size} bytes, {config_count} configs) ───")
        asm_lines.append("    .global kConfigsZst")
        asm_lines.append("kConfigsZst:")
        asm_lines.append(f'    .incbin "{zst_filename}"')
        asm_lines.append("    .global kConfigsZstLen")
        asm_lines.append("kConfigsZstLen:")
        asm_lines.append(f"    .quad {embed_size}")
    else:
        asm_lines.append("// ─── config bundle (not available) ───")
        asm_lines.append("    .global kConfigsZst")
        asm_lines.append("kConfigsZst:")
        asm_lines.append("    .byte 0")
        asm_lines.append("    .global kConfigsZstLen")
        asm_lines.append("kConfigsZstLen:")
        asm_lines.append("    .quad 0")
    asm_lines.append("")
    (out_dir / "config_embedded.S").write_text("\n".join(asm_lines))

    # ─── Generate config_meta.json ───
    meta = {
        "app": "Hunter Censorship Hunter",
        "kind": "configs",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "compressed": use_zstd if have_bundle else False,
        "config_count": config_count,
        "original_size": orig_size,
        "embedded_size": embed_size,
        "sha256": sha256,
        "source": "Downloaded at build time from 25+ public GitHub sources via tools/download_configs.py",
    }
    (out_dir / "config_meta.json").write_text(json.dumps(meta, indent=2))

    print(f"[cfg-embed] wrote config_embedded.h, config_embedded.S, config_meta.json to {out_dir}")
    print(f"[cfg-embed] HAS_CONFIGS={1 if have_bundle else 0}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
