#!/usr/bin/env python3
"""
embed_gl_fallback.py — Bake a software-OpenGL fallback into the Windows
single-file Hunter build (opengl32.dll + libgallium_wgl.dll from Mesa3D's
mesa-dist-win project: https://github.com/pal1000/mesa-dist-win).

Why this exists: some real Windows machines have no working hardware OpenGL
driver at all — VMs with a 2D-only display adapter (QXL, Basic Display Adapter),
some RDP sessions, very old GPUs. On those, GLFW's window/context creation
fails outright (WGL error "The driver does not appear to support OpenGL") and
the GUI can never open. Dropping Mesa's opengl32.dll + libgallium_wgl.dll next
to the .exe fixes this via software rendering, because implicit DLL imports
resolve from the application directory before System32.

Windows-only. Mirrors tools/embed_engines.py's .incbin approach but is kept
as a separate script/namespace (HUNTER_GL_FALLBACK_* / kGlFallback* symbols)
rather than folded into embed_engines.py's engine list, so
HUNTER_EMBED_HAS_ENGINES keeps meaning exactly "xray/sing-box are embedded"
and never gets muddied by an unrelated payload.

At runtime (src/core/gl_fallback_embed_win.cpp, Windows-only) this is used
ONLY as a fallback: hunter.exe tries hardware OpenGL first; if and only if
window/context creation fails, it extracts these two files next to itself,
forces GALLIUM_DRIVER=softpipe (Mesa's non-JIT interpreter — llvmpipe's LLVM
JIT gets killed by hardened endpoint security on some machines because JIT
compilation needs RWX memory, a classic shellcode-injection heuristic), and
relaunches itself once.

Usage:
  embed_gl_fallback.py --bin <dir with opengl32.dll + libgallium_wgl.dll>
                        --outdir <build_dir> [--zstd <path>] [--no-zstd]
"""
import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

FILES = [
    # (filename, symbol prefix)
    ("opengl32.dll", "kGlFallbackLoader"),
    ("libgallium_wgl.dll", "kGlFallbackDriver"),
]

SOURCE_URL = "https://github.com/pal1000/mesa-dist-win/releases"


def zstd_compress(path: Path, zstd_bin: str, out_path: Path) -> bytes:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [zstd_bin, "-19", "-f", "-q", "-o", str(out_path), str(path)]
    subprocess.check_call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out_path.read_bytes()


def main():
    ap = argparse.ArgumentParser(description="Embed the Mesa software-OpenGL fallback via .incbin.")
    ap.add_argument("--bin", required=True, help="Directory containing opengl32.dll + libgallium_wgl.dll.")
    ap.add_argument("--outdir", required=True, help="Output directory for generated files.")
    ap.add_argument("--zstd", default=shutil.which("zstd") or "zstd", help="zstd CLI path.")
    ap.add_argument("--no-zstd", action="store_true", help="Embed raw bytes (no compression).")
    args = ap.parse_args()

    bin_dir = Path(args.bin)
    out_dir = Path(args.outdir)
    out_dir.mkdir(parents=True, exist_ok=True)

    use_zstd = not args.no_zstd
    if use_zstd and not shutil.which(args.zstd):
        print(f"[gl-fallback-embed] WARNING: zstd CLI '{args.zstd}' not found; raw embed.", file=sys.stderr)
        use_zstd = False

    items = []
    have_all = True
    for filename, sym in FILES:
        path = bin_dir / filename
        if not path.exists() or path.stat().st_size == 0:
            print(f"[gl-fallback-embed] {filename}: not found in {bin_dir} — GL fallback disabled.", file=sys.stderr)
            have_all = False
            items.append({"filename": filename, "symbol_prefix": sym, "found": False,
                          "orig_size": 0, "embed_size": 0, "sha256": "", "zst_filename": ""})
            continue

        raw = path.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        ext = ".zst" if use_zstd else ".bin"
        blob_path = out_dir / f"{sym}{ext}"
        comp = zstd_compress(path, args.zstd, blob_path) if use_zstd else (shutil.copy2(path, blob_path), blob_path.read_bytes())[1]
        ratio = (len(comp) / len(raw) * 100.0) if raw else 0.0
        print(f"[gl-fallback-embed] {filename}: {len(raw)} -> {len(comp)} bytes ({ratio:.1f}%) sha256={digest[:12]}...")
        items.append({"filename": filename, "symbol_prefix": sym, "found": True,
                      "orig_size": len(raw), "embed_size": len(comp), "sha256": digest,
                      "zst_filename": blob_path.name})

    # ─── header ───
    header_lines = [
        "// AUTO-GENERATED by tools/embed_gl_fallback.py — DO NOT EDIT.",
        "// Software-OpenGL fallback (Mesa opengl32.dll + libgallium_wgl.dll), Windows-only.",
        f"// Compressed with zstd (-19): {use_zstd}",
        "",
        "#pragma once",
        "",
        f"#define HUNTER_GL_FALLBACK_EMBEDDED {1 if have_all else 0}",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for it in items:
        sym = it["symbol_prefix"]
        header_lines.append(f"// ─── {it['filename']} ───")
        header_lines.append(f"extern const unsigned char {sym}Zst[];")
        header_lines.append(f"extern const unsigned long  {sym}ZstLen;")
        header_lines.append(f"static const unsigned long  {sym}OrigLen = {it['orig_size']};")
        header_lines.append("")
    header_lines += ["#ifdef __cplusplus", "}", "#endif", ""]
    (out_dir / "gl_fallback_embedded.h").write_text("\n".join(header_lines))

    # ─── assembler (.incbin) — custom section, same reasoning as engine embed ───
    asm_lines = [
        "// AUTO-GENERATED by tools/embed_gl_fallback.py — DO NOT EDIT.",
        "// Self-contained — no #include (all values baked in at generation time).",
        "",
        '    .section .hunterdat,"dr"',
        "",
    ]
    for it in items:
        sym = it["symbol_prefix"]
        if it["found"]:
            asm_lines.append(f"// ─── {it['filename']} ({it['embed_size']} bytes) ───")
            asm_lines.append(f"    .global {sym}Zst")
            asm_lines.append(f"{sym}Zst:")
            asm_lines.append(f'    .incbin "{it["zst_filename"]}"')
            asm_lines.append(f"    .global {sym}ZstLen")
            asm_lines.append(f"{sym}ZstLen:")
            asm_lines.append(f"    .quad {it['embed_size']}")
        else:
            asm_lines.append(f"// ─── {it['filename']} (not available) ───")
            asm_lines.append(f"    .global {sym}Zst")
            asm_lines.append(f"{sym}Zst:")
            asm_lines.append(f"    .byte 0")
            asm_lines.append(f"    .global {sym}ZstLen")
            asm_lines.append(f"{sym}ZstLen:")
            asm_lines.append(f"    .quad 0")
        asm_lines.append("")
    (out_dir / "gl_fallback_embedded.S").write_text("\n".join(asm_lines))

    meta = {
        "app": "Hunter Censorship Hunter",
        "kind": "gl_fallback",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "compressed": use_zstd,
        "source_url": SOURCE_URL,
        "files": {it["filename"]: {k: v for k, v in it.items() if k != "filename"} for it in items},
    }
    (out_dir / "gl_fallback_meta.json").write_text(json.dumps(meta, indent=2))

    print(f"[gl-fallback-embed] wrote gl_fallback_embedded.h/.S, gl_fallback_meta.json to {out_dir}")
    print(f"[gl-fallback-embed] HUNTER_GL_FALLBACK_EMBEDDED={1 if have_all else 0}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
